
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7"><![endif]-->
<!--[if lt IE 9]><html class="no-js lte-ie8"><![endif]-->
<!--[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>Working with errors in Ruby: begin, rescue and ensure - Greg Osborn</title>
  <meta name="author" content="Greg Osborn">

  
  <meta name="description" content="Seeing Ruby throw an exception when you don&rsquo;t expect it can be pretty frusturating. At this point in my programming career, most of them are &hellip;">
  

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <link rel="canonical" href="http://gosborn.github.io/blog/2015/07/17/working-with-errors-in-ruby-catch-and-throw">
  <link href="/favicon.ico" rel="icon">
  
  <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
  <script src="/javascripts/modernizr-2.0.js"></script>
  <script src="/javascripts/ender.js"></script>
  <script src="/javascripts/octopress.js" type="text/javascript"></script>
  <link href="/atom.xml" rel="alternate" title="Greg Osborn" type="application/atom+xml">
  <!--Fonts from Google"s Web font directory at http://google.com/webfonts -->
<link href="http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">

  

</head>

<body   class="no-sidebar"  >
  <header role="banner"><hgroup>
  <h1>Greg Osborn</h1>
  
    <h2><a href="/">GO!</a></h2>
  
</hgroup>

</header>
  <nav role="navigation">
  
<form action="https://www.google.com/search" method="get">
  <fieldset role="search">
    <input type="hidden" name="q" value="site:gosborn.github.io" />
    <input class="search" type="text" name="q" results="0" placeholder="Search"/>
  </fieldset>
</form>
  
<ul class="main-navigation">
  <li><a href="/">Blog</a></li>
  <li><a href="/blog/archives">Archives</a></li>
</ul>

</nav>
  <div id="main">
    <div id="content">
      <div>
<article class="hentry" role="article">
  
  <header>
    
      <h1 class="entry-title">Working With Errors in Ruby: Begin, Rescue and Ensure</h1>
    
    
      <p class="meta">
        








  


<time datetime="2015-07-17T08:55:08-04:00" pubdate data-updated="true"></time>
        
      </p>
    
  </header>


<div class="entry-content"><p>Seeing Ruby throw an exception when you don&rsquo;t expect it can be pretty frusturating. At this point in my programming career, most of them are user created. Ruby raises pretty specific exceptions and even a backtrace to figure out where you went wrong. Usually my protocol is to do find the error, figure out where my logic or typing went wrong and restart my program.</p>

<p>But sometimes exceptions arise in your program and they&rsquo;re not your fault. Lately, I&rsquo;ve been working on a database of beer that is populated with information from an online database, <a href="http://www.brewerydb.com/">breweryDB</a>. To gather the info, I&rsquo;m getting JSON files from their API with a method like this:</p>

<figure class='code'><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
<span class='line-number'>2</span>
<span class='line-number'>3</span>
</pre></td><td class='code'><pre><code class=''><span class='line'>def load_db_json(input)
</span><span class='line'>  JSON.load(RestClient.get("http://api.brewerydb.com/v2/" + input)
</span><span class='line'>end
</span></code></pre></td></tr></table></div></figure>


<p>Specifically, I&rsquo;m downloading JSON files that provide me ids to find all the beers from a group of breweries.</p>

<figure class='code'><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
<span class='line-number'>2</span>
<span class='line-number'>3</span>
<span class='line-number'>4</span>
<span class='line-number'>5</span>
<span class='line-number'>6</span>
<span class='line-number'>7</span>
<span class='line-number'>8</span>
<span class='line-number'>9</span>
<span class='line-number'>10</span>
<span class='line-number'>11</span>
<span class='line-number'>12</span>
</pre></td><td class='code'><pre><code class=''><span class='line'>def all_beers_from_brewery(brewery)
</span><span class='line'>  load_db_json("brewery/#{brewery.db_code}/beers?key=#{@key}")["data"]
</span><span class='line'>end
</span><span class='line'>
</span><span class='line'>@state.breweries.each do |brewery|
</span><span class='line'>  if !all_beers_from_brewery(brewery).nil?
</span><span class='line'>    all_beers_from_brewery(brewery).each do |hash|
</span><span class='line'>      brewery.beers.build(name: hash["name"], db_code: hash["id"], abv: hash["abv"], ibu: hash["ibu"], description: hash["description"])
</span><span class='line'>      brewery.save
</span><span class='line'>    end
</span><span class='line'>  end
</span><span class='line'>end
</span></code></pre></td></tr></table></div></figure>


<p>The above code uses the brewery ids to find the beers associated with it, and build ActiveRecord associated objects. But it doesn&rsquo;t always work.</p>

<p>Sometimes the breweries will be missing from the database and so when I try to get a json from a missing page, I get a fun exception:</p>

<p>RestClient::ResourceNotFound: 404 Resource Not Found</p>

<p>And my program stops. Since I&rsquo;m iterating through a long list of breweries, this is super annoying, because no subsequent data will be entered into my database. This is where Ruby&rsquo;s catch, throw and ensure methods come in.</p>

<figure class='code'><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
<span class='line-number'>2</span>
<span class='line-number'>3</span>
<span class='line-number'>4</span>
<span class='line-number'>5</span>
<span class='line-number'>6</span>
<span class='line-number'>7</span>
<span class='line-number'>8</span>
<span class='line-number'>9</span>
</pre></td><td class='code'><pre><code class=''><span class='line'>begin
</span><span class='line'>  a + a
</span><span class='line'>rescue =&gt; e
</span><span class='line'>  puts e
</span><span class='line'>ensure
</span><span class='line'>  puts "we'll be fine, regardless of what happens"
</span><span class='line'>end
</span><span class='line'>undefined local variable or method `a' for main:Object
</span><span class='line'>we'll be fine, regardless of what happens
</span></code></pre></td></tr></table></div></figure>


<p>If this code was just written as below, it would break, because a isn&rsquo;t defined.</p>

<figure class='code'><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
</pre></td><td class='code'><pre><code class=''><span class='line'>a + a</span></code></pre></td></tr></table></div></figure>


<p>Using begin, rescue and ensure allows you to negotiate the error and keep moving. It&rsquo;s a little hacky to solve ordinary problems, but when working with large datasets that might fail because of errors in the members of the dataset, it can be super helpful.</p>

<p>The above isn&rsquo;t super different than an if/else statement, except that the error is handled and the code continues. Here&rsquo;s how I use it in real life:</p>

<figure class='code'><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
<span class='line-number'>2</span>
<span class='line-number'>3</span>
<span class='line-number'>4</span>
<span class='line-number'>5</span>
<span class='line-number'>6</span>
<span class='line-number'>7</span>
<span class='line-number'>8</span>
</pre></td><td class='code'><pre><code class=''><span class='line'>def all_beers_from_brewery(brewery)
</span><span class='line'>  begin
</span><span class='line'>    load_db_json("brewery/#{brewery.db_code}/beers?key=#{@key}")["data"]
</span><span class='line'>  rescue =&gt; error
</span><span class='line'>    retry
</span><span class='line'>    puts "#{error} for #{brewery.name}"
</span><span class='line'>  end
</span><span class='line'>end
</span></code></pre></td></tr></table></div></figure>


<p>Now if I get an error iterating through my database with the below code, I don&rsquo;t break the operation, I just get an error message and move on with the parsing:</p>

<figure class='code'><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
<span class='line-number'>2</span>
<span class='line-number'>3</span>
<span class='line-number'>4</span>
<span class='line-number'>5</span>
<span class='line-number'>6</span>
</pre></td><td class='code'><pre><code class=''><span class='line'>@state.breweries.each do |brewery|
</span><span class='line'>    all_beers_from_brewery(brewery).each do |hash|
</span><span class='line'>      brewery.beers.build(name: hash["name"], db_code: hash["id"], abv: hash["abv"], ibu: hash["ibu"], description: hash["description"])
</span><span class='line'>      brewery.save
</span><span class='line'>    end
</span><span class='line'>end
</span></code></pre></td></tr></table></div></figure>


<p>Javascript and Python have very similar operations. Javascript uses &ldquo;try, throw and catch, finally&rdquo; and Python uses &ldquo;try, except and finally&rdquo;.</p>

<p>Here are some resources to learn more:</p>

<p><a href="http://ruby.bastardsbook.com/chapters/exception-handling/">Ruby Bastards: exception handling</a><br/>
<a href="http://rubylearning.com/satishtalim/ruby_exceptions.html">Ruby Learning: exceptions</a><br/>
<a href="https://blog.newrelic.com/2014/12/10/weird-ruby-2-rescue-interrupt-ensure/">Weird Ruby, rescue and interrupt</a><br/>
<a href="https://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/41-exceptions/lessons/92-handling">Ruby Monk: handling exceptions</a><br/>
<a href="http://www.jiaaro.com/pythonjavascript-trick-hacky-error-handling/">Exception handling in JS and Python</a></p>
</div>


  <footer>
    <p class="meta">
      
  

<span class="byline author vcard">Posted by <span class="fn"><a href="/about" title="About the author (Greg Osborn)" rel="author">Greg Osborn</a></span></span>

      








  


<time datetime="2015-07-17T08:55:08-04:00" pubdate data-updated="true"></time>
      


    </p>
    
      <div class="sharing">
  
  <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://gosborn.github.io/blog/2015/07/17/working-with-errors-in-ruby-catch-and-throw/" data-via="" data-counturl="http://gosborn.github.io/blog/2015/07/17/working-with-errors-in-ruby-catch-and-throw/" >Tweet</a>
  
  
  
</div>

    
    <p class="meta">
      
        <a class="basic-alignment left" href="/blog/2015/07/01/start-using-pry/" title="Previous Post: Start using Pry!">&laquo; Start using Pry!</a>
      
      
        <a class="basic-alignment right" href="/blog/2015/07/29/making-cronjobs-easy-with-whenever/" title="next Post: Making cron jobs easy with whenever">Making cron jobs easy with whenever &raquo;</a>
      
    </p>
  </footer>
</article>

</div>


    </div>
  </div>
  <footer role="contentinfo"><p>
  Copyright &copy; 2015 - Greg Osborn -
  <span class="credit">Powered by <a href="http://octopress.org">Octopress</a></span>
</p>

</footer>
  







  <script type="text/javascript">
    (function(){
      var twitterWidgets = document.createElement('script');
      twitterWidgets.type = 'text/javascript';
      twitterWidgets.async = true;
      twitterWidgets.src = 'http://platform.twitter.com/widgets.js';
      document.getElementsByTagName('head')[0].appendChild(twitterWidgets);
    })();
  </script>





</body>
</html>
